spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/Local?useSSL=false&&characterEncoding=UTF-8
  jpa:
    show-sql: true
  server:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##    level: info
#  path: /log/springlog
